version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d myapp"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    environment:
      PORT: "5000"
      DATABASE_URL: postgresql://user:password@db:5432/myapp
      JWT_SECRET_KEY: dev-secret
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: sh -c "flask db upgrade && gunicorn --bind 0.0.0.0:5000 --workers 2 --threads 8 --timeout 120 'app:create_app()'"

volumes:
  postgres_data: