"""add users.email

Revision ID: 637bbe430998
Revises: 65472a05823d
Create Date: 2025-08-19 15:11:05.791666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637bbe430998'
down_revision = '65472a05823d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
