"""empty message

Revision ID: 65472a05823d
Revises: 84092750fd33
Create Date: 2025-08-17 00:13:10.553479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65472a05823d'
down_revision = '84092750fd33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
